### ISSUE TITLE
iocp does not build using gcc 15.2 on Windows

### ISSUE THREAD

**Issue by PaulObermeier** [apnadkarni/iocp#24]
**Error message:**
```
In file included from win/tclWinIocp.h:37,
                 from win/tclWinIocpUtil.c:13:
win/tclhUuid.h:196:10: error: conflicting types for 'Tclh_NewUuidObj'; have 'Tcl_Obj *(Tcl_Interp *)'
  196 | Tcl_Obj *Tclh_NewUuidObj (Tcl_Interp *ip)
      |          ^~~~~~~~~~~~~~~
win/tclhUuid.h:22:10: note: previous declaration of 'Tclh_NewUuidObj' with type 'Tcl_Obj *(void)'
   22 | Tcl_Obj *Tclh_NewUuidObj ();
```

**Solution:**
Add `Tcl_Interp *ip` to declaration of Tclh_NewUuidObj.
